version: "3"

services:
  trained_model:
    build: ./flask_app
    restart: always
    command: gunicorn --bind 0.0.0.0:5050 app:app
    volumes:
      - ./:/flask_app
    ports:
      - "5050:5050"
    expose:
      - "5050"

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "5000:80"